/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockOracleInterface extends Interface {
    getFunction(nameOrSignature: "getPrice" | "prices" | "setPrice"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getPrice', values: [AddressLike, AddressLike, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'prices', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setPrice', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrice', data: BytesLike): Result;
  }

  

  export interface MockOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockOracle;
    waitForDeployment(): Promise<this>;

    interface: MockOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getPrice: TypedContractMethod<
      [token: AddressLike, quoteToken: AddressLike, arg2: BytesLike[], ],
      [bigint],
      'view'
    >
    

    
    prices: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setPrice: TypedContractMethod<
      [token: AddressLike, quoteToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [token: AddressLike, quoteToken: AddressLike, arg2: BytesLike[], ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'prices'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setPrice'): TypedContractMethod<
      [token: AddressLike, quoteToken: AddressLike, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }