/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEIP1271, IEIP1271Interface } from "../../interfaces/IEIP1271.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_hash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "_signature",
        "type": "bytes"
      }
    ],
    "name": "isValidSignature",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "magicValue",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IEIP1271__factory {
    static readonly abi = _abi;
    static createInterface(): IEIP1271Interface {
      return new Interface(_abi) as IEIP1271Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEIP1271 {
      return new Contract(address, _abi, runner) as unknown as IEIP1271;
    }
  }
  