/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IFeeHandler, IFeeHandlerInterface } from "../../interfaces/IFeeHandler.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "ProvisionFees",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "accounts",
        "type": "address[]"
      },
      {
        "indexed": false,
        "internalType": "uint256[]",
        "name": "feeShares",
        "type": "uint256[]"
      }
    ],
    "name": "SetDistPartnerFeeShares",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "exerciseFee",
        "type": "uint96"
      }
    ],
    "name": "SetExerciseFee",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "matchFee",
        "type": "uint256"
      }
    ],
    "name": "SetMatchFee",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "underlyingTokens",
        "type": "address[]"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "settlementTokens",
        "type": "address[]"
      },
      {
        "components": [
          {
            "internalType": "bool",
            "name": "isSet",
            "type": "bool"
          },
          {
            "internalType": "uint96",
            "name": "matchFee",
            "type": "uint96"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.MatchFeePerPair[]",
        "name": "matchFeesPerPair",
        "type": "tuple[]"
      }
    ],
    "name": "SetMatchFeesPerPair",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "mintFee",
        "type": "uint256"
      }
    ],
    "name": "SetMintFee",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Withdraw",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "distPartnerFeeShare",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "exerciseFee",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "",
        "type": "uint96"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      },
      {
        "internalType": "uint128",
        "name": "optionPremium",
        "type": "uint128"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "expiry",
            "type": "uint48"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "earliestExercise",
            "type": "uint48"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "strike",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.OptionInfo",
        "name": "optionInfo",
        "type": "tuple"
      }
    ],
    "name": "getMatchFeeInfo",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "_matchFee",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_matchFeeDistPartnerShare",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "getMintFeeInfo",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "_mintFee",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_mintFeeDistPartnerShare",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "matchFee",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "",
        "type": "uint96"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "provisionFees",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "accounts",
        "type": "address[]"
      },
      {
        "internalType": "uint256[]",
        "name": "feeShares",
        "type": "uint256[]"
      }
    ],
    "name": "setDistPartnerFeeShares",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint96",
        "name": "_exerciseFee",
        "type": "uint96"
      }
    ],
    "name": "setExerciseFee",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint96",
        "name": "_matchFee",
        "type": "uint96"
      }
    ],
    "name": "setMatchFee",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "underlyingTokens",
        "type": "address[]"
      },
      {
        "internalType": "address[]",
        "name": "settlementTokens",
        "type": "address[]"
      },
      {
        "components": [
          {
            "internalType": "bool",
            "name": "isSet",
            "type": "bool"
          },
          {
            "internalType": "uint96",
            "name": "matchFee",
            "type": "uint96"
          }
        ],
        "internalType": "struct DataTypes.MatchFeePerPair[]",
        "name": "_matchFeePerPair",
        "type": "tuple[]"
      }
    ],
    "name": "setMatchFeesPerPair",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IFeeHandler__factory {
    static readonly abi = _abi;
    static createInterface(): IFeeHandlerInterface {
      return new Interface(_abi) as IFeeHandlerInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IFeeHandler {
      return new Contract(address, _abi, runner) as unknown as IFeeHandler;
    }
  }
  