/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IOracleAdapter, IOracleAdapterInterface } from "../../interfaces/IOracleAdapter.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "oracleAddress",
        "type": "address"
      }
    ],
    "name": "AddOracleMapping",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "ETH_USD_ORACLE",
    "outputs": [
      {
        "internalType": "address",
        "name": "ethUsdOracle",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_TIME_SINCE_LAST_UPDATE",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "maxTime",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "ORACLE_MAPPING_IS_APPEND_ONLY",
    "outputs": [
      {
        "internalType": "bool",
        "name": "isAppendOnly",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "WETH",
    "outputs": [
      {
        "internalType": "address",
        "name": "weth",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "tokenAddrs",
        "type": "address[]"
      },
      {
        "internalType": "address[]",
        "name": "oracleAddrs",
        "type": "address[]"
      }
    ],
    "name": "addOracleMapping",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "quoteToken",
        "type": "address"
      },
      {
        "internalType": "bytes[]",
        "name": "oracleData",
        "type": "bytes[]"
      }
    ],
    "name": "getPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "tokenPriceInQuoteToken",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "getPriceOfToken",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "tokenPriceRaw",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "oracleInfos",
    "outputs": [
      {
        "internalType": "address",
        "name": "oracleAddr",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "decimals",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IOracleAdapter__factory {
    static readonly abi = _abi;
    static createInterface(): IOracleAdapterInterface {
      return new Interface(_abi) as IOracleAdapterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IOracleAdapter {
      return new Contract(address, _abi, runner) as unknown as IOracleAdapter;
    }
  }
  