/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRouter, IRouterInterface } from "../../interfaces/IRouter.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "optionReceiver",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "enum DataTypes.BidStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "strike",
            "type": "uint128"
          },
          {
            "internalType": "uint48",
            "name": "expiry",
            "type": "uint48"
          },
          {
            "internalType": "uint48",
            "name": "earliestExercise",
            "type": "uint48"
          },
          {
            "internalType": "uint128",
            "name": "premium",
            "type": "uint128"
          },
          {
            "internalType": "address",
            "name": "premiumToken",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "oracleSpotPrice",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "currAsk",
            "type": "uint64"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeProtocol",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeDistPartner",
            "type": "uint128"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.BidPreview",
        "name": "bidPreview",
        "type": "tuple"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "BidOnAuction",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "underlyingReceiver",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "underlyingAmount",
        "type": "uint128"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "collateralAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "collateralFeeAmount",
        "type": "uint256"
      }
    ],
    "name": "Borrow",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "relStrike",
                "type": "uint128"
              },
              {
                "internalType": "uint48",
                "name": "tenor",
                "type": "uint48"
              },
              {
                "internalType": "uint48",
                "name": "earliestExerciseTenor",
                "type": "uint48"
              },
              {
                "internalType": "uint32",
                "name": "decayStartTime",
                "type": "uint32"
              },
              {
                "internalType": "uint32",
                "name": "decayDuration",
                "type": "uint32"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumStart",
                "type": "uint64"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumFloor",
                "type": "uint64"
              },
              {
                "internalType": "uint128",
                "name": "minSpot",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "maxSpot",
                "type": "uint128"
              }
            ],
            "internalType": "struct DataTypes.AuctionParams",
            "name": "auctionParams",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.AuctionInitialization",
        "name": "auctionInitialization",
        "type": "tuple"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "exerciseFee",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "CreateAuction",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "underlyingReceiver",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "underlyingAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "exerciseFeeAmount",
        "type": "uint256"
      }
    ],
    "name": "Exercise",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "optionReceiver",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "expiry",
            "type": "uint48"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "earliestExercise",
            "type": "uint48"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "strike",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.OptionInfo",
        "name": "optionInfo",
        "type": "tuple"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "mintFeeProtocol",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "mintFeeDistPartner",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "MintOption",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "oldFeeHandler",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "newFeeHandler",
        "type": "address"
      }
    ],
    "name": "NewFeeHandler",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "spaceId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "delegate",
        "type": "address"
      }
    ],
    "name": "OffChainVotingDelegation",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "delegate",
        "type": "address"
      }
    ],
    "name": "OnChainVotingDelegation",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "quoter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "isPaused",
        "type": "bool"
      }
    ],
    "name": "PauseQuotes",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "collateralReceiver",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "repayUnderlyingAmount",
        "type": "uint128"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "unlockedCollateralAmount",
        "type": "uint256"
      }
    ],
    "name": "Repay",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "components": [
          {
            "components": [
              {
                "internalType": "address",
                "name": "underlyingToken",
                "type": "address"
              },
              {
                "internalType": "uint48",
                "name": "expiry",
                "type": "uint48"
              },
              {
                "internalType": "address",
                "name": "settlementToken",
                "type": "address"
              },
              {
                "internalType": "uint48",
                "name": "earliestExercise",
                "type": "uint48"
              },
              {
                "internalType": "uint128",
                "name": "notional",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "strike",
                "type": "uint128"
              },
              {
                "components": [
                  {
                    "internalType": "uint64",
                    "name": "borrowCap",
                    "type": "uint64"
                  },
                  {
                    "internalType": "address",
                    "name": "oracle",
                    "type": "address"
                  },
                  {
                    "internalType": "bool",
                    "name": "premiumTokenIsUnderlying",
                    "type": "bool"
                  },
                  {
                    "internalType": "bool",
                    "name": "votingDelegationAllowed",
                    "type": "bool"
                  },
                  {
                    "internalType": "address",
                    "name": "allowedDelegateRegistry",
                    "type": "address"
                  }
                ],
                "internalType": "struct DataTypes.AdvancedSettings",
                "name": "advancedSettings",
                "type": "tuple"
              }
            ],
            "internalType": "struct DataTypes.OptionInfo",
            "name": "optionInfo",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "premium",
                "type": "uint128"
              },
              {
                "internalType": "uint256",
                "name": "validUntil",
                "type": "uint256"
              },
              {
                "internalType": "bytes",
                "name": "signature",
                "type": "bytes"
              },
              {
                "internalType": "address",
                "name": "eip1271Maker",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.RFQQuote",
            "name": "rfqQuote",
            "type": "tuple"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.RFQInitialization",
        "name": "rfqInitialization",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "enum DataTypes.RFQStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "bytes32",
            "name": "msgHash",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "quoter",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "premium",
            "type": "uint128"
          },
          {
            "internalType": "address",
            "name": "premiumToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeProtocol",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeDistPartner",
            "type": "uint128"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.TakeQuotePreview",
        "name": "takeQuotePreview",
        "type": "tuple"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "exerciseFee",
        "type": "uint96"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "TakeQuote",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "maker",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "takerGiveToken",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "takerGiveAmount",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "makerGiveToken",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "makerGiveAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validUntil",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "signature",
            "type": "bytes"
          },
          {
            "internalType": "address",
            "name": "eip1271Maker",
            "type": "address"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.SwapQuote",
        "name": "swapQuote",
        "type": "tuple"
      }
    ],
    "name": "TakeSwapQuote",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "Transfer",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "TransferOwnership",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Withdraw",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "oldEscrow",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newEscrow",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "relStrike",
                "type": "uint128"
              },
              {
                "internalType": "uint48",
                "name": "tenor",
                "type": "uint48"
              },
              {
                "internalType": "uint48",
                "name": "earliestExerciseTenor",
                "type": "uint48"
              },
              {
                "internalType": "uint32",
                "name": "decayStartTime",
                "type": "uint32"
              },
              {
                "internalType": "uint32",
                "name": "decayDuration",
                "type": "uint32"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumStart",
                "type": "uint64"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumFloor",
                "type": "uint64"
              },
              {
                "internalType": "uint128",
                "name": "minSpot",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "maxSpot",
                "type": "uint128"
              }
            ],
            "internalType": "struct DataTypes.AuctionParams",
            "name": "auctionParams",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "indexed": false,
        "internalType": "struct DataTypes.AuctionInitialization",
        "name": "auctionInitialization",
        "type": "tuple"
      }
    ],
    "name": "WithdrawFromEscrowAndCreateAuction",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "optionReceiver",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "relBid",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "refSpot",
        "type": "uint256"
      },
      {
        "internalType": "bytes[]",
        "name": "oracleData",
        "type": "bytes[]"
      }
    ],
    "name": "bidOnAuction",
    "outputs": [
      {
        "components": [
          {
            "internalType": "enum DataTypes.BidStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "strike",
            "type": "uint128"
          },
          {
            "internalType": "uint48",
            "name": "expiry",
            "type": "uint48"
          },
          {
            "internalType": "uint48",
            "name": "earliestExercise",
            "type": "uint48"
          },
          {
            "internalType": "uint128",
            "name": "premium",
            "type": "uint128"
          },
          {
            "internalType": "address",
            "name": "premiumToken",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "oracleSpotPrice",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "currAsk",
            "type": "uint64"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeProtocol",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeDistPartner",
            "type": "uint128"
          }
        ],
        "internalType": "struct DataTypes.BidPreview",
        "name": "preview",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "underlyingReceiver",
        "type": "address"
      },
      {
        "internalType": "uint128",
        "name": "borrowUnderlyingAmount",
        "type": "uint128"
      }
    ],
    "name": "borrow",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "relStrike",
                "type": "uint128"
              },
              {
                "internalType": "uint48",
                "name": "tenor",
                "type": "uint48"
              },
              {
                "internalType": "uint48",
                "name": "earliestExerciseTenor",
                "type": "uint48"
              },
              {
                "internalType": "uint32",
                "name": "decayStartTime",
                "type": "uint32"
              },
              {
                "internalType": "uint32",
                "name": "decayDuration",
                "type": "uint32"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumStart",
                "type": "uint64"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumFloor",
                "type": "uint64"
              },
              {
                "internalType": "uint128",
                "name": "minSpot",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "maxSpot",
                "type": "uint128"
              }
            ],
            "internalType": "struct DataTypes.AuctionParams",
            "name": "auctionParams",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.AuctionInitialization",
        "name": "auctionInitialization",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "createAuction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "emitTransferEvent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "oldOwner",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "emitTransferOwnershipEvent",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "escrowImpl",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "underlyingReceiver",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "underlyingAmount",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "payInSettlementToken",
        "type": "bool"
      },
      {
        "internalType": "bytes[]",
        "name": "oracleData",
        "type": "bytes[]"
      }
    ],
    "name": "exercise",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feeHandler",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "from",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "numElements",
        "type": "uint256"
      }
    ],
    "name": "getEscrows",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "_escrows",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getExerciseFee",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "exerciseFee",
        "type": "uint96"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      },
      {
        "internalType": "uint128",
        "name": "optionPremium",
        "type": "uint128"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "expiry",
            "type": "uint48"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "earliestExercise",
            "type": "uint48"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "strike",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.OptionInfo",
        "name": "optionInfo",
        "type": "tuple"
      }
    ],
    "name": "getMatchFees",
    "outputs": [
      {
        "internalType": "uint128",
        "name": "matchFeeProtocol",
        "type": "uint128"
      },
      {
        "internalType": "uint128",
        "name": "matchFeeDistPartner",
        "type": "uint128"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      },
      {
        "internalType": "uint128",
        "name": "notional",
        "type": "uint128"
      }
    ],
    "name": "getMintFees",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "mintFeeProtocol",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "mintFeeDistPartner",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "spaceId",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "delegate",
        "type": "address"
      }
    ],
    "name": "handleOffChainVoting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "delegate",
        "type": "address"
      }
    ],
    "name": "handleOnChainVoting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      }
    ],
    "name": "isEscrow",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "quoteHash",
        "type": "bytes32"
      }
    ],
    "name": "isQuoteUsed",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "swapQuoteHash",
        "type": "bytes32"
      }
    ],
    "name": "isSwapQuoteUsed",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "optionReceiver",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "expiry",
            "type": "uint48"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint48",
            "name": "earliestExercise",
            "type": "uint48"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "strike",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.OptionInfo",
        "name": "optionInfo",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "symbol",
            "type": "string"
          }
        ],
        "internalType": "struct DataTypes.OptionNaming",
        "name": "optionNaming",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "mintOption",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "numEscrows",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "internalType": "address",
                "name": "underlyingToken",
                "type": "address"
              },
              {
                "internalType": "uint48",
                "name": "expiry",
                "type": "uint48"
              },
              {
                "internalType": "address",
                "name": "settlementToken",
                "type": "address"
              },
              {
                "internalType": "uint48",
                "name": "earliestExercise",
                "type": "uint48"
              },
              {
                "internalType": "uint128",
                "name": "notional",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "strike",
                "type": "uint128"
              },
              {
                "components": [
                  {
                    "internalType": "uint64",
                    "name": "borrowCap",
                    "type": "uint64"
                  },
                  {
                    "internalType": "address",
                    "name": "oracle",
                    "type": "address"
                  },
                  {
                    "internalType": "bool",
                    "name": "premiumTokenIsUnderlying",
                    "type": "bool"
                  },
                  {
                    "internalType": "bool",
                    "name": "votingDelegationAllowed",
                    "type": "bool"
                  },
                  {
                    "internalType": "address",
                    "name": "allowedDelegateRegistry",
                    "type": "address"
                  }
                ],
                "internalType": "struct DataTypes.AdvancedSettings",
                "name": "advancedSettings",
                "type": "tuple"
              }
            ],
            "internalType": "struct DataTypes.OptionInfo",
            "name": "optionInfo",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "premium",
                "type": "uint128"
              },
              {
                "internalType": "uint256",
                "name": "validUntil",
                "type": "uint256"
              },
              {
                "internalType": "bytes",
                "name": "signature",
                "type": "bytes"
              },
              {
                "internalType": "address",
                "name": "eip1271Maker",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.RFQQuote",
            "name": "rfqQuote",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.RFQInitialization",
        "name": "rfqInitialization",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "previewTakeQuote",
    "outputs": [
      {
        "components": [
          {
            "internalType": "enum DataTypes.RFQStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "bytes32",
            "name": "msgHash",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "quoter",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "premium",
            "type": "uint128"
          },
          {
            "internalType": "address",
            "name": "premiumToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeProtocol",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "matchFeeDistPartner",
            "type": "uint128"
          }
        ],
        "internalType": "struct DataTypes.TakeQuotePreview",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "quoter",
        "type": "address"
      }
    ],
    "name": "quotesPaused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "collateralReceiver",
        "type": "address"
      },
      {
        "internalType": "uint128",
        "name": "repayUnderlyingAmount",
        "type": "uint128"
      }
    ],
    "name": "repay",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newFeeHandler",
        "type": "address"
      }
    ],
    "name": "setFeeHandler",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "components": [
          {
            "components": [
              {
                "internalType": "address",
                "name": "underlyingToken",
                "type": "address"
              },
              {
                "internalType": "uint48",
                "name": "expiry",
                "type": "uint48"
              },
              {
                "internalType": "address",
                "name": "settlementToken",
                "type": "address"
              },
              {
                "internalType": "uint48",
                "name": "earliestExercise",
                "type": "uint48"
              },
              {
                "internalType": "uint128",
                "name": "notional",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "strike",
                "type": "uint128"
              },
              {
                "components": [
                  {
                    "internalType": "uint64",
                    "name": "borrowCap",
                    "type": "uint64"
                  },
                  {
                    "internalType": "address",
                    "name": "oracle",
                    "type": "address"
                  },
                  {
                    "internalType": "bool",
                    "name": "premiumTokenIsUnderlying",
                    "type": "bool"
                  },
                  {
                    "internalType": "bool",
                    "name": "votingDelegationAllowed",
                    "type": "bool"
                  },
                  {
                    "internalType": "address",
                    "name": "allowedDelegateRegistry",
                    "type": "address"
                  }
                ],
                "internalType": "struct DataTypes.AdvancedSettings",
                "name": "advancedSettings",
                "type": "tuple"
              }
            ],
            "internalType": "struct DataTypes.OptionInfo",
            "name": "optionInfo",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "premium",
                "type": "uint128"
              },
              {
                "internalType": "uint256",
                "name": "validUntil",
                "type": "uint256"
              },
              {
                "internalType": "bytes",
                "name": "signature",
                "type": "bytes"
              },
              {
                "internalType": "address",
                "name": "eip1271Maker",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.RFQQuote",
            "name": "rfqQuote",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.RFQInitialization",
        "name": "rfqInitialization",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "takeQuote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "takerGiveToken",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "takerGiveAmount",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "makerGiveToken",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "makerGiveAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validUntil",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "signature",
            "type": "bytes"
          },
          {
            "internalType": "address",
            "name": "eip1271Maker",
            "type": "address"
          }
        ],
        "internalType": "struct DataTypes.SwapQuote",
        "name": "swapQuote",
        "type": "tuple"
      }
    ],
    "name": "takeSwapQuote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "togglePauseQuotes",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "escrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "oldEscrow",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "escrowOwner",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "underlyingToken",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "settlementToken",
            "type": "address"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          },
          {
            "components": [
              {
                "internalType": "uint128",
                "name": "relStrike",
                "type": "uint128"
              },
              {
                "internalType": "uint48",
                "name": "tenor",
                "type": "uint48"
              },
              {
                "internalType": "uint48",
                "name": "earliestExerciseTenor",
                "type": "uint48"
              },
              {
                "internalType": "uint32",
                "name": "decayStartTime",
                "type": "uint32"
              },
              {
                "internalType": "uint32",
                "name": "decayDuration",
                "type": "uint32"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumStart",
                "type": "uint64"
              },
              {
                "internalType": "uint64",
                "name": "relPremiumFloor",
                "type": "uint64"
              },
              {
                "internalType": "uint128",
                "name": "minSpot",
                "type": "uint128"
              },
              {
                "internalType": "uint128",
                "name": "maxSpot",
                "type": "uint128"
              }
            ],
            "internalType": "struct DataTypes.AuctionParams",
            "name": "auctionParams",
            "type": "tuple"
          },
          {
            "components": [
              {
                "internalType": "uint64",
                "name": "borrowCap",
                "type": "uint64"
              },
              {
                "internalType": "address",
                "name": "oracle",
                "type": "address"
              },
              {
                "internalType": "bool",
                "name": "premiumTokenIsUnderlying",
                "type": "bool"
              },
              {
                "internalType": "bool",
                "name": "votingDelegationAllowed",
                "type": "bool"
              },
              {
                "internalType": "address",
                "name": "allowedDelegateRegistry",
                "type": "address"
              }
            ],
            "internalType": "struct DataTypes.AdvancedSettings",
            "name": "advancedSettings",
            "type": "tuple"
          }
        ],
        "internalType": "struct DataTypes.AuctionInitialization",
        "name": "auctionInitialization",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "distPartner",
        "type": "address"
      }
    ],
    "name": "withdrawFromEscrowAndCreateAuction",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IRouter__factory {
    static readonly abi = _abi;
    static createInterface(): IRouterInterface {
      return new Interface(_abi) as IRouterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRouter {
      return new Contract(address, _abi, runner) as unknown as IRouter;
    }
  }
  