// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

library Errors {
    error DistPartnerFeeAlreadySet();
    error FeeHandlerAlreadySet();
    error InvalidAddress();
    error InvalidArrayLength();
    error InvalidBid();
    error InvalidBorrowAmount();
    error InvalidBorrowCap();
    error InvalidBorrowTime();
    error InvalidDistPartnerFeeShare();
    error InvalidEarliestExercise();
    error InvalidEarliestExerciseTenor();
    error InvalidEIP1271Signature();
    error InvalidExpiry();
    error InvalidExercise();
    error InvalidExerciseAmount();
    error InvalidExerciseFee();
    error InvalidExerciseTime();
    error InvalidGetEscrowsQuery();
    error InvalidMatchFee();
    error InvalidMaxTimeSinceLastUpdate();
    error InvalidMinMaxSpot();
    error InvalidNotional();
    error InvalidOracle();
    error InvalidOracleAnswer();
    error InvalidOracleDecimals();
    error InvalidRedeem();
    error InvalidRelPremiums();
    error InvalidRepayAmount();
    error InvalidRepayTime();
    error InvalidSender();
    error InvalidStrike();
    error InvalidTakeQuote();
    error InvalidTenor();
    error InvalidTokenPair();
    error InvalidWithdraw();
    error NoAllowedDelegateRegistry();
    error NoOptionMinted();
    error NoOracle();
    error NotAnEscrow();
    error NothingToRedeem();
    error NothingToRepay();
    error OracleAlreadySet(address oracleAddr);
    error OwnerAlreadySet();
    error SwapQuoteAlreadyUsed();
    error SwapQuoteExpired();
    error SwapQuotePaused();
    error VotingDelegationNotAllowed();
}
