/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DataTypes {
      
    export type BidPreviewStruct = {status: BigNumberish, settlementToken: AddressLike, underlyingToken: AddressLike, strike: BigNumberish, expiry: BigNumberish, earliestExercise: BigNumberish, premium: BigNumberish, premiumToken: AddressLike, oracleSpotPrice: BigNumberish, currAsk: BigNumberish, matchFeeProtocol: BigNumberish, matchFeeDistPartner: BigNumberish}

    export type BidPreviewStructOutput = [status: bigint, settlementToken: string, underlyingToken: string, strike: bigint, expiry: bigint, earliestExercise: bigint, premium: bigint, premiumToken: string, oracleSpotPrice: bigint, currAsk: bigint, matchFeeProtocol: bigint, matchFeeDistPartner: bigint] & {status: bigint, settlementToken: string, underlyingToken: string, strike: bigint, expiry: bigint, earliestExercise: bigint, premium: bigint, premiumToken: string, oracleSpotPrice: bigint, currAsk: bigint, matchFeeProtocol: bigint, matchFeeDistPartner: bigint }
  

    export type AuctionParamsStruct = {relStrike: BigNumberish, tenor: BigNumberish, earliestExerciseTenor: BigNumberish, decayStartTime: BigNumberish, decayDuration: BigNumberish, relPremiumStart: BigNumberish, relPremiumFloor: BigNumberish, minSpot: BigNumberish, maxSpot: BigNumberish}

    export type AuctionParamsStructOutput = [relStrike: bigint, tenor: bigint, earliestExerciseTenor: bigint, decayStartTime: bigint, decayDuration: bigint, relPremiumStart: bigint, relPremiumFloor: bigint, minSpot: bigint, maxSpot: bigint] & {relStrike: bigint, tenor: bigint, earliestExerciseTenor: bigint, decayStartTime: bigint, decayDuration: bigint, relPremiumStart: bigint, relPremiumFloor: bigint, minSpot: bigint, maxSpot: bigint }
  

    export type AdvancedSettingsStruct = {borrowCap: BigNumberish, oracle: AddressLike, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: AddressLike}

    export type AdvancedSettingsStructOutput = [borrowCap: bigint, oracle: string, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: string] & {borrowCap: bigint, oracle: string, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: string }
  

    export type AuctionInitializationStruct = {underlyingToken: AddressLike, settlementToken: AddressLike, notional: BigNumberish, auctionParams: DataTypes.AuctionParamsStruct, advancedSettings: DataTypes.AdvancedSettingsStruct}

    export type AuctionInitializationStructOutput = [underlyingToken: string, settlementToken: string, notional: bigint, auctionParams: DataTypes.AuctionParamsStructOutput, advancedSettings: DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, settlementToken: string, notional: bigint, auctionParams: DataTypes.AuctionParamsStructOutput, advancedSettings: DataTypes.AdvancedSettingsStructOutput }
  

    export type OptionInfoStruct = {underlyingToken: AddressLike, expiry: BigNumberish, settlementToken: AddressLike, earliestExercise: BigNumberish, notional: BigNumberish, strike: BigNumberish, advancedSettings: DataTypes.AdvancedSettingsStruct}

    export type OptionInfoStructOutput = [underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput }
  

    export type OptionNamingStruct = {name: string, symbol: string}

    export type OptionNamingStructOutput = [name: string, symbol: string] & {name: string, symbol: string }
  

    export type RFQQuoteStruct = {premium: BigNumberish, validUntil: BigNumberish, signature: BytesLike, eip1271Maker: AddressLike}

    export type RFQQuoteStructOutput = [premium: bigint, validUntil: bigint, signature: string, eip1271Maker: string] & {premium: bigint, validUntil: bigint, signature: string, eip1271Maker: string }
  

    export type RFQInitializationStruct = {optionInfo: DataTypes.OptionInfoStruct, rfqQuote: DataTypes.RFQQuoteStruct}

    export type RFQInitializationStructOutput = [optionInfo: DataTypes.OptionInfoStructOutput, rfqQuote: DataTypes.RFQQuoteStructOutput] & {optionInfo: DataTypes.OptionInfoStructOutput, rfqQuote: DataTypes.RFQQuoteStructOutput }
  
    }

  export interface EscrowInterface extends Interface {
    getFunction(nameOrSignature: "allowance" | "approve" | "auctionParams" | "balanceOf" | "borrowedUnderlyingAmounts" | "currAsk" | "decimals" | "distPartner" | "exerciseFee" | "handleAuctionBid" | "handleBorrow" | "handleExercise" | "handleOffChainVoting" | "handleOnChainVoting" | "handleRepay" | "handleWithdraw" | "initializeAuction" | "initializeMintOption" | "initializeRFQMatch" | "isAuction" | "name" | "optionInfo" | "optionMinted" | "owner" | "premiumPaid" | "previewBid" | "redeem" | "router" | "symbol" | "totalBorrowed" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "Initialized" | "OffChainVotingDelegation" | "OnChainVotingDelegation" | "Redeem" | "Transfer" | "TransferOwnership" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'auctionParams', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'borrowedUnderlyingAmounts', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'currAsk', values?: undefined): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'distPartner', values?: undefined): string;
encodeFunctionData(functionFragment: 'exerciseFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'handleAuctionBid', values: [BigNumberish, AddressLike, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'handleBorrow', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'handleExercise', values: [AddressLike, AddressLike, BigNumberish, boolean, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'handleOffChainVoting', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'handleOnChainVoting', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'handleRepay', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'handleWithdraw', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initializeAuction', values: [AddressLike, AddressLike, BigNumberish, DataTypes.AuctionInitializationStruct, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'initializeMintOption', values: [AddressLike, AddressLike, AddressLike, BigNumberish, DataTypes.OptionInfoStruct, DataTypes.OptionNamingStruct]): string;
encodeFunctionData(functionFragment: 'initializeRFQMatch', values: [AddressLike, AddressLike, AddressLike, BigNumberish, DataTypes.RFQInitializationStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isAuction', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'optionInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'optionMinted', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'premiumPaid', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewBid', values: [BigNumberish, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'redeem', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'router', values?: undefined): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalBorrowed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctionParams', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrowedUnderlyingAmounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currAsk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distPartner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exerciseFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleAuctionBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleBorrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleExercise', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOffChainVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOnChainVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleRepay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeMintOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initializeRFQMatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'optionInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'optionMinted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'premiumPaid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBorrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OffChainVotingDelegationEvent {
      export type InputTuple = [allowedDelegateRegistry: AddressLike, spaceId: BytesLike, delegate: AddressLike];
      export type OutputTuple = [allowedDelegateRegistry: string, spaceId: string, delegate: string];
      export interface OutputObject {allowedDelegateRegistry: string, spaceId: string, delegate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OnChainVotingDelegationEvent {
      export type InputTuple = [delegate: AddressLike];
      export type OutputTuple = [delegate: string];
      export interface OutputObject {delegate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemEvent {
      export type InputTuple = [sender: AddressLike, to: AddressLike, underlyingToken: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, to: string, underlyingToken: string, amount: bigint];
      export interface OutputObject {sender: string, to: string, underlyingToken: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferOwnershipEvent {
      export type InputTuple = [sender: AddressLike, oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [sender: string, oldOwner: string, newOwner: string];
      export interface OutputObject {sender: string, oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [sender: AddressLike, to: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, to: string, token: string, amount: bigint];
      export interface OutputObject {sender: string, to: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Escrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): Escrow;
    waitForDeployment(): Promise<this>;

    interface: EscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    auctionParams: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {relStrike: bigint, tenor: bigint, earliestExerciseTenor: bigint, decayStartTime: bigint, decayDuration: bigint, relPremiumStart: bigint, relPremiumFloor: bigint, minSpot: bigint, maxSpot: bigint }],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    borrowedUnderlyingAmounts: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    currAsk: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    distPartner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    exerciseFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    handleAuctionBid: TypedContractMethod<
      [relBid: BigNumberish, optionReceiver: AddressLike, _refSpot: BigNumberish, _oracleData: BytesLike[], ],
      [[DataTypes.BidPreviewStructOutput, string] & {preview: DataTypes.BidPreviewStructOutput, __distPartner: string }],
      'nonpayable'
    >
    

    
    handleBorrow: TypedContractMethod<
      [borrower: AddressLike, underlyingReceiver: AddressLike, underlyingBorrowAmount: BigNumberish, ],
      [[string, bigint, bigint] & {settlementToken: string, collateralAmount: bigint, collateralFeeAmount: bigint }],
      'nonpayable'
    >
    

    
    handleExercise: TypedContractMethod<
      [exerciser: AddressLike, underlyingReceiver: AddressLike, underlyingExerciseAmount: BigNumberish, payInSettlementToken: boolean, oracleData: BytesLike[], ],
      [[string, bigint, bigint] & {settlementToken: string, settlementAmount: bigint, exerciseFeeAmount: bigint }],
      'nonpayable'
    >
    

    
    handleOffChainVoting: TypedContractMethod<
      [spaceId: BytesLike, delegate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    handleOnChainVoting: TypedContractMethod<
      [delegate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    handleRepay: TypedContractMethod<
      [borrower: AddressLike, collateralReceiver: AddressLike, underlyingRepayAmount: BigNumberish, ],
      [[string, bigint] & {underlyingToken: string, unlockedCollateralAmount: bigint }],
      'nonpayable'
    >
    

    
    handleWithdraw: TypedContractMethod<
      [to: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    initializeAuction: TypedContractMethod<
      [_router: AddressLike, _owner: AddressLike, _exerciseFee: BigNumberish, _auctionInitialization: DataTypes.AuctionInitializationStruct, oTokenIndex: BigNumberish, __distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    initializeMintOption: TypedContractMethod<
      [_router: AddressLike, _owner: AddressLike, optionReceiver: AddressLike, _exerciseFee: BigNumberish, _optionInfo: DataTypes.OptionInfoStruct, _optionNaming: DataTypes.OptionNamingStruct, ],
      [void],
      'nonpayable'
    >
    

    
    initializeRFQMatch: TypedContractMethod<
      [_router: AddressLike, _owner: AddressLike, optionReceiver: AddressLike, _exerciseFee: BigNumberish, _rfqInitialization: DataTypes.RFQInitializationStruct, oTokenIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isAuction: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    optionInfo: TypedContractMethod<
      [],
      [[string, bigint, string, bigint, bigint, bigint, DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput }],
      'view'
    >
    

    
    optionMinted: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    premiumPaid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    previewBid: TypedContractMethod<
      [relBid: BigNumberish, _refSpot: BigNumberish, _oracleData: BytesLike[], ],
      [[DataTypes.BidPreviewStructOutput, string] & {preview: DataTypes.BidPreviewStructOutput, __distPartner: string }],
      'view'
    >
    

    
    redeem: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalBorrowed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'auctionParams'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {relStrike: bigint, tenor: bigint, earliestExerciseTenor: bigint, decayStartTime: bigint, decayDuration: bigint, relPremiumStart: bigint, relPremiumFloor: bigint, minSpot: bigint, maxSpot: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'borrowedUnderlyingAmounts'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currAsk'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distPartner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'exerciseFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'handleAuctionBid'): TypedContractMethod<
      [relBid: BigNumberish, optionReceiver: AddressLike, _refSpot: BigNumberish, _oracleData: BytesLike[], ],
      [[DataTypes.BidPreviewStructOutput, string] & {preview: DataTypes.BidPreviewStructOutput, __distPartner: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleBorrow'): TypedContractMethod<
      [borrower: AddressLike, underlyingReceiver: AddressLike, underlyingBorrowAmount: BigNumberish, ],
      [[string, bigint, bigint] & {settlementToken: string, collateralAmount: bigint, collateralFeeAmount: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleExercise'): TypedContractMethod<
      [exerciser: AddressLike, underlyingReceiver: AddressLike, underlyingExerciseAmount: BigNumberish, payInSettlementToken: boolean, oracleData: BytesLike[], ],
      [[string, bigint, bigint] & {settlementToken: string, settlementAmount: bigint, exerciseFeeAmount: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleOffChainVoting'): TypedContractMethod<
      [spaceId: BytesLike, delegate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleOnChainVoting'): TypedContractMethod<
      [delegate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleRepay'): TypedContractMethod<
      [borrower: AddressLike, collateralReceiver: AddressLike, underlyingRepayAmount: BigNumberish, ],
      [[string, bigint] & {underlyingToken: string, unlockedCollateralAmount: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleWithdraw'): TypedContractMethod<
      [to: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeAuction'): TypedContractMethod<
      [_router: AddressLike, _owner: AddressLike, _exerciseFee: BigNumberish, _auctionInitialization: DataTypes.AuctionInitializationStruct, oTokenIndex: BigNumberish, __distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeMintOption'): TypedContractMethod<
      [_router: AddressLike, _owner: AddressLike, optionReceiver: AddressLike, _exerciseFee: BigNumberish, _optionInfo: DataTypes.OptionInfoStruct, _optionNaming: DataTypes.OptionNamingStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initializeRFQMatch'): TypedContractMethod<
      [_router: AddressLike, _owner: AddressLike, optionReceiver: AddressLike, _exerciseFee: BigNumberish, _rfqInitialization: DataTypes.RFQInitializationStruct, oTokenIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAuction'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'optionInfo'): TypedContractMethod<
      [],
      [[string, bigint, string, bigint, bigint, bigint, DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput }],
      'view'
    >;
getFunction(nameOrSignature: 'optionMinted'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'premiumPaid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewBid'): TypedContractMethod<
      [relBid: BigNumberish, _refSpot: BigNumberish, _oracleData: BytesLike[], ],
      [[DataTypes.BidPreviewStructOutput, string] & {preview: DataTypes.BidPreviewStructOutput, __distPartner: string }],
      'view'
    >;
getFunction(nameOrSignature: 'redeem'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalBorrowed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OffChainVotingDelegation'): TypedContractEvent<OffChainVotingDelegationEvent.InputTuple, OffChainVotingDelegationEvent.OutputTuple, OffChainVotingDelegationEvent.OutputObject>;
getEvent(key: 'OnChainVotingDelegation'): TypedContractEvent<OnChainVotingDelegationEvent.InputTuple, OnChainVotingDelegationEvent.OutputTuple, OnChainVotingDelegationEvent.OutputObject>;
getEvent(key: 'Redeem'): TypedContractEvent<RedeemEvent.InputTuple, RedeemEvent.OutputTuple, RedeemEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TransferOwnership'): TypedContractEvent<TransferOwnershipEvent.InputTuple, TransferOwnershipEvent.OutputTuple, TransferOwnershipEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OffChainVotingDelegation(address,bytes32,address)': TypedContractEvent<OffChainVotingDelegationEvent.InputTuple, OffChainVotingDelegationEvent.OutputTuple, OffChainVotingDelegationEvent.OutputObject>;
      OffChainVotingDelegation: TypedContractEvent<OffChainVotingDelegationEvent.InputTuple, OffChainVotingDelegationEvent.OutputTuple, OffChainVotingDelegationEvent.OutputObject>;
    

      'OnChainVotingDelegation(address)': TypedContractEvent<OnChainVotingDelegationEvent.InputTuple, OnChainVotingDelegationEvent.OutputTuple, OnChainVotingDelegationEvent.OutputObject>;
      OnChainVotingDelegation: TypedContractEvent<OnChainVotingDelegationEvent.InputTuple, OnChainVotingDelegationEvent.OutputTuple, OnChainVotingDelegationEvent.OutputObject>;
    

      'Redeem(address,address,address,uint256)': TypedContractEvent<RedeemEvent.InputTuple, RedeemEvent.OutputTuple, RedeemEvent.OutputObject>;
      Redeem: TypedContractEvent<RedeemEvent.InputTuple, RedeemEvent.OutputTuple, RedeemEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TransferOwnership(address,address,address)': TypedContractEvent<TransferOwnershipEvent.InputTuple, TransferOwnershipEvent.OutputTuple, TransferOwnershipEvent.OutputObject>;
      TransferOwnership: TypedContractEvent<TransferOwnershipEvent.InputTuple, TransferOwnershipEvent.OutputTuple, TransferOwnershipEvent.OutputObject>;
    

      'Withdraw(address,address,address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }