/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Escrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Escrow__factory>
getContractFactory(name: 'Router', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Router__factory>
getContractFactory(name: 'Errors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Errors__factory>
getContractFactory(name: 'FeeHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FeeHandler__factory>
getContractFactory(name: 'IDelegation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IDelegation__factory>
getContractFactory(name: 'IEIP1271', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEIP1271__factory>
getContractFactory(name: 'IEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEscrow__factory>
getContractFactory(name: 'IFeeHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFeeHandler__factory>
getContractFactory(name: 'IOracleAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOracleAdapter__factory>
getContractFactory(name: 'IRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRouter__factory>
getContractFactory(name: 'OracleAdapter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OracleAdapter__factory>
getContractFactory(name: 'EIP1271Maker', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EIP1271Maker__factory>
getContractFactory(name: 'MockAggregatorV3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAggregatorV3__factory>
getContractFactory(name: 'MockDelegateRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockDelegateRegistry__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockERC20Votes', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20Votes__factory>
getContractFactory(name: 'MockHighFeeHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockHighFeeHandler__factory>
getContractFactory(name: 'MockOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockOracle__factory>
getContractFactory(name: 'TestInitializableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TestInitializableERC20__factory>
getContractFactory(name: 'TestRecover', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TestRecover__factory>
getContractFactory(name: 'InitializableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InitializableERC20__factory>

  getContractAt(name: 'Escrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Escrow>
getContractAt(name: 'Router', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Router>
getContractAt(name: 'Errors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Errors>
getContractAt(name: 'FeeHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FeeHandler>
getContractAt(name: 'IDelegation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IDelegation>
getContractAt(name: 'IEIP1271', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEIP1271>
getContractAt(name: 'IEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEscrow>
getContractAt(name: 'IFeeHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFeeHandler>
getContractAt(name: 'IOracleAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOracleAdapter>
getContractAt(name: 'IRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRouter>
getContractAt(name: 'OracleAdapter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OracleAdapter>
getContractAt(name: 'EIP1271Maker', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EIP1271Maker>
getContractAt(name: 'MockAggregatorV3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAggregatorV3>
getContractAt(name: 'MockDelegateRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockDelegateRegistry>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockERC20Votes', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20Votes>
getContractAt(name: 'MockHighFeeHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockHighFeeHandler>
getContractAt(name: 'MockOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockOracle>
getContractAt(name: 'TestInitializableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TestInitializableERC20>
getContractAt(name: 'TestRecover', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TestRecover>
getContractAt(name: 'InitializableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InitializableERC20>

  deployContract(name: 'Escrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Escrow>
deployContract(name: 'Router', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Router>
deployContract(name: 'Errors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Errors>
deployContract(name: 'FeeHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeHandler>
deployContract(name: 'IDelegation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDelegation>
deployContract(name: 'IEIP1271', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEIP1271>
deployContract(name: 'IEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrow>
deployContract(name: 'IFeeHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeHandler>
deployContract(name: 'IOracleAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOracleAdapter>
deployContract(name: 'IRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRouter>
deployContract(name: 'OracleAdapter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OracleAdapter>
deployContract(name: 'EIP1271Maker', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EIP1271Maker>
deployContract(name: 'MockAggregatorV3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAggregatorV3>
deployContract(name: 'MockDelegateRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockDelegateRegistry>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC20Votes', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20Votes>
deployContract(name: 'MockHighFeeHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockHighFeeHandler>
deployContract(name: 'MockOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockOracle>
deployContract(name: 'TestInitializableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestInitializableERC20>
deployContract(name: 'TestRecover', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestRecover>
deployContract(name: 'InitializableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InitializableERC20>

  deployContract(name: 'Escrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Escrow>
deployContract(name: 'Router', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Router>
deployContract(name: 'Errors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Errors>
deployContract(name: 'FeeHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeHandler>
deployContract(name: 'IDelegation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDelegation>
deployContract(name: 'IEIP1271', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEIP1271>
deployContract(name: 'IEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrow>
deployContract(name: 'IFeeHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeHandler>
deployContract(name: 'IOracleAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOracleAdapter>
deployContract(name: 'IRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRouter>
deployContract(name: 'OracleAdapter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OracleAdapter>
deployContract(name: 'EIP1271Maker', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EIP1271Maker>
deployContract(name: 'MockAggregatorV3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAggregatorV3>
deployContract(name: 'MockDelegateRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockDelegateRegistry>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockERC20Votes', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20Votes>
deployContract(name: 'MockHighFeeHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockHighFeeHandler>
deployContract(name: 'MockOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockOracle>
deployContract(name: 'TestInitializableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestInitializableERC20>
deployContract(name: 'TestRecover', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestRecover>
deployContract(name: 'InitializableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InitializableERC20>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  