/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DataTypes {
      
    export type BidPreviewStruct = {status: BigNumberish, settlementToken: AddressLike, underlyingToken: AddressLike, strike: BigNumberish, expiry: BigNumberish, earliestExercise: BigNumberish, premium: BigNumberish, premiumToken: AddressLike, oracleSpotPrice: BigNumberish, currAsk: BigNumberish, matchFeeProtocol: BigNumberish, matchFeeDistPartner: BigNumberish}

    export type BidPreviewStructOutput = [status: bigint, settlementToken: string, underlyingToken: string, strike: bigint, expiry: bigint, earliestExercise: bigint, premium: bigint, premiumToken: string, oracleSpotPrice: bigint, currAsk: bigint, matchFeeProtocol: bigint, matchFeeDistPartner: bigint] & {status: bigint, settlementToken: string, underlyingToken: string, strike: bigint, expiry: bigint, earliestExercise: bigint, premium: bigint, premiumToken: string, oracleSpotPrice: bigint, currAsk: bigint, matchFeeProtocol: bigint, matchFeeDistPartner: bigint }
  

    export type AuctionParamsStruct = {relStrike: BigNumberish, tenor: BigNumberish, earliestExerciseTenor: BigNumberish, decayStartTime: BigNumberish, decayDuration: BigNumberish, relPremiumStart: BigNumberish, relPremiumFloor: BigNumberish, minSpot: BigNumberish, maxSpot: BigNumberish}

    export type AuctionParamsStructOutput = [relStrike: bigint, tenor: bigint, earliestExerciseTenor: bigint, decayStartTime: bigint, decayDuration: bigint, relPremiumStart: bigint, relPremiumFloor: bigint, minSpot: bigint, maxSpot: bigint] & {relStrike: bigint, tenor: bigint, earliestExerciseTenor: bigint, decayStartTime: bigint, decayDuration: bigint, relPremiumStart: bigint, relPremiumFloor: bigint, minSpot: bigint, maxSpot: bigint }
  

    export type AdvancedSettingsStruct = {borrowCap: BigNumberish, oracle: AddressLike, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: AddressLike}

    export type AdvancedSettingsStructOutput = [borrowCap: bigint, oracle: string, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: string] & {borrowCap: bigint, oracle: string, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: string }
  

    export type AuctionInitializationStruct = {underlyingToken: AddressLike, settlementToken: AddressLike, notional: BigNumberish, auctionParams: DataTypes.AuctionParamsStruct, advancedSettings: DataTypes.AdvancedSettingsStruct}

    export type AuctionInitializationStructOutput = [underlyingToken: string, settlementToken: string, notional: bigint, auctionParams: DataTypes.AuctionParamsStructOutput, advancedSettings: DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, settlementToken: string, notional: bigint, auctionParams: DataTypes.AuctionParamsStructOutput, advancedSettings: DataTypes.AdvancedSettingsStructOutput }
  

    export type OptionInfoStruct = {underlyingToken: AddressLike, expiry: BigNumberish, settlementToken: AddressLike, earliestExercise: BigNumberish, notional: BigNumberish, strike: BigNumberish, advancedSettings: DataTypes.AdvancedSettingsStruct}

    export type OptionInfoStructOutput = [underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput }
  

    export type RFQQuoteStruct = {premium: BigNumberish, validUntil: BigNumberish, signature: BytesLike, eip1271Maker: AddressLike}

    export type RFQQuoteStructOutput = [premium: bigint, validUntil: bigint, signature: string, eip1271Maker: string] & {premium: bigint, validUntil: bigint, signature: string, eip1271Maker: string }
  

    export type RFQInitializationStruct = {optionInfo: DataTypes.OptionInfoStruct, rfqQuote: DataTypes.RFQQuoteStruct}

    export type RFQInitializationStructOutput = [optionInfo: DataTypes.OptionInfoStructOutput, rfqQuote: DataTypes.RFQQuoteStructOutput] & {optionInfo: DataTypes.OptionInfoStructOutput, rfqQuote: DataTypes.RFQQuoteStructOutput }
  

    export type TakeQuotePreviewStruct = {status: BigNumberish, msgHash: BytesLike, quoter: AddressLike, premium: BigNumberish, premiumToken: AddressLike, matchFeeProtocol: BigNumberish, matchFeeDistPartner: BigNumberish}

    export type TakeQuotePreviewStructOutput = [status: bigint, msgHash: string, quoter: string, premium: bigint, premiumToken: string, matchFeeProtocol: bigint, matchFeeDistPartner: bigint] & {status: bigint, msgHash: string, quoter: string, premium: bigint, premiumToken: string, matchFeeProtocol: bigint, matchFeeDistPartner: bigint }
  

    export type SwapQuoteStruct = {takerGiveToken: AddressLike, takerGiveAmount: BigNumberish, makerGiveToken: AddressLike, makerGiveAmount: BigNumberish, validUntil: BigNumberish, signature: BytesLike, eip1271Maker: AddressLike}

    export type SwapQuoteStructOutput = [takerGiveToken: string, takerGiveAmount: bigint, makerGiveToken: string, makerGiveAmount: bigint, validUntil: bigint, signature: string, eip1271Maker: string] & {takerGiveToken: string, takerGiveAmount: bigint, makerGiveToken: string, makerGiveAmount: bigint, validUntil: bigint, signature: string, eip1271Maker: string }
  

    export type OptionNamingStruct = {name: string, symbol: string}

    export type OptionNamingStructOutput = [name: string, symbol: string] & {name: string, symbol: string }
  
    }

  export interface RouterInterface extends Interface {
    getFunction(nameOrSignature: "bidOnAuction" | "borrow" | "createAuction" | "emitTransferEvent" | "emitTransferOwnershipEvent" | "escrowImpl" | "exercise" | "feeHandler" | "getEscrows" | "getExerciseFee" | "getMatchFees" | "getMintFees" | "handleOffChainVoting" | "handleOnChainVoting" | "isEscrow" | "isQuoteUsed" | "isSwapQuoteUsed" | "mintOption" | "numEscrows" | "owner" | "previewTakeQuote" | "quotesPaused" | "renounceOwnership" | "repay" | "setFeeHandler" | "takeQuote" | "takeSwapQuote" | "togglePauseQuotes" | "transferOwnership" | "withdraw" | "withdrawFromEscrowAndCreateAuction"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BidOnAuction" | "Borrow" | "CreateAuction" | "Exercise" | "MintOption" | "NewFeeHandler" | "OffChainVotingDelegation" | "OnChainVotingDelegation" | "OwnershipTransferred" | "PauseQuotes" | "Repay" | "TakeQuote" | "TakeSwapQuote" | "Transfer" | "TransferOwnership" | "Withdraw" | "WithdrawFromEscrowAndCreateAuction"): EventFragment;

    encodeFunctionData(functionFragment: 'bidOnAuction', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'borrow', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [AddressLike, DataTypes.AuctionInitializationStruct, AddressLike]): string;
encodeFunctionData(functionFragment: 'emitTransferEvent', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'emitTransferOwnershipEvent', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'escrowImpl', values?: undefined): string;
encodeFunctionData(functionFragment: 'exercise', values: [AddressLike, AddressLike, BigNumberish, boolean, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'feeHandler', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEscrows', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getExerciseFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMatchFees', values: [AddressLike, BigNumberish, DataTypes.OptionInfoStruct]): string;
encodeFunctionData(functionFragment: 'getMintFees', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'handleOffChainVoting', values: [AddressLike, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'handleOnChainVoting', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isEscrow', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isQuoteUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isSwapQuoteUsed', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'mintOption', values: [AddressLike, AddressLike, DataTypes.OptionInfoStruct, DataTypes.OptionNamingStruct, AddressLike]): string;
encodeFunctionData(functionFragment: 'numEscrows', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewTakeQuote', values: [DataTypes.RFQInitializationStruct, AddressLike]): string;
encodeFunctionData(functionFragment: 'quotesPaused', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'repay', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setFeeHandler', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'takeQuote', values: [AddressLike, DataTypes.RFQInitializationStruct, AddressLike]): string;
encodeFunctionData(functionFragment: 'takeSwapQuote', values: [AddressLike, DataTypes.SwapQuoteStruct]): string;
encodeFunctionData(functionFragment: 'togglePauseQuotes', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFromEscrowAndCreateAuction', values: [AddressLike, AddressLike, DataTypes.AuctionInitializationStruct, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'bidOnAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emitTransferEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emitTransferOwnershipEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowImpl', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exercise', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeHandler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getExerciseFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMatchFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMintFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOffChainVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOnChainVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isQuoteUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSwapQuoteUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintOption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'numEscrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewTakeQuote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quotesPaused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeHandler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeQuote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'takeSwapQuote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'togglePauseQuotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFromEscrowAndCreateAuction', data: BytesLike): Result;
  }

  
    export namespace BidOnAuctionEvent {
      export type InputTuple = [sender: AddressLike, escrow: AddressLike, optionReceiver: AddressLike, bidPreview: DataTypes.BidPreviewStruct, distPartner: AddressLike];
      export type OutputTuple = [sender: string, escrow: string, optionReceiver: string, bidPreview: DataTypes.BidPreviewStructOutput, distPartner: string];
      export interface OutputObject {sender: string, escrow: string, optionReceiver: string, bidPreview: DataTypes.BidPreviewStructOutput, distPartner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BorrowEvent {
      export type InputTuple = [sender: AddressLike, escrow: AddressLike, underlyingReceiver: AddressLike, underlyingAmount: BigNumberish, collateralAmount: BigNumberish, collateralFeeAmount: BigNumberish];
      export type OutputTuple = [sender: string, escrow: string, underlyingReceiver: string, underlyingAmount: bigint, collateralAmount: bigint, collateralFeeAmount: bigint];
      export interface OutputObject {sender: string, escrow: string, underlyingReceiver: string, underlyingAmount: bigint, collateralAmount: bigint, collateralFeeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreateAuctionEvent {
      export type InputTuple = [escrowOwner: AddressLike, escrow: AddressLike, auctionInitialization: DataTypes.AuctionInitializationStruct, exerciseFee: BigNumberish, distPartner: AddressLike];
      export type OutputTuple = [escrowOwner: string, escrow: string, auctionInitialization: DataTypes.AuctionInitializationStructOutput, exerciseFee: bigint, distPartner: string];
      export interface OutputObject {escrowOwner: string, escrow: string, auctionInitialization: DataTypes.AuctionInitializationStructOutput, exerciseFee: bigint, distPartner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExerciseEvent {
      export type InputTuple = [sender: AddressLike, escrow: AddressLike, underlyingReceiver: AddressLike, underlyingAmount: BigNumberish, exerciseFeeAmount: BigNumberish];
      export type OutputTuple = [sender: string, escrow: string, underlyingReceiver: string, underlyingAmount: bigint, exerciseFeeAmount: bigint];
      export interface OutputObject {sender: string, escrow: string, underlyingReceiver: string, underlyingAmount: bigint, exerciseFeeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintOptionEvent {
      export type InputTuple = [sender: AddressLike, optionReceiver: AddressLike, escrowOwner: AddressLike, optionInfo: DataTypes.OptionInfoStruct, mintFeeProtocol: BigNumberish, mintFeeDistPartner: BigNumberish, distPartner: AddressLike];
      export type OutputTuple = [sender: string, optionReceiver: string, escrowOwner: string, optionInfo: DataTypes.OptionInfoStructOutput, mintFeeProtocol: bigint, mintFeeDistPartner: bigint, distPartner: string];
      export interface OutputObject {sender: string, optionReceiver: string, escrowOwner: string, optionInfo: DataTypes.OptionInfoStructOutput, mintFeeProtocol: bigint, mintFeeDistPartner: bigint, distPartner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NewFeeHandlerEvent {
      export type InputTuple = [oldFeeHandler: AddressLike, newFeeHandler: AddressLike];
      export type OutputTuple = [oldFeeHandler: string, newFeeHandler: string];
      export interface OutputObject {oldFeeHandler: string, newFeeHandler: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OffChainVotingDelegationEvent {
      export type InputTuple = [escrow: AddressLike, spaceId: BytesLike, delegate: AddressLike];
      export type OutputTuple = [escrow: string, spaceId: string, delegate: string];
      export interface OutputObject {escrow: string, spaceId: string, delegate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OnChainVotingDelegationEvent {
      export type InputTuple = [escrow: AddressLike, delegate: AddressLike];
      export type OutputTuple = [escrow: string, delegate: string];
      export interface OutputObject {escrow: string, delegate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PauseQuotesEvent {
      export type InputTuple = [quoter: AddressLike, isPaused: boolean];
      export type OutputTuple = [quoter: string, isPaused: boolean];
      export interface OutputObject {quoter: string, isPaused: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepayEvent {
      export type InputTuple = [sender: AddressLike, escrow: AddressLike, collateralReceiver: AddressLike, repayUnderlyingAmount: BigNumberish, unlockedCollateralAmount: BigNumberish];
      export type OutputTuple = [sender: string, escrow: string, collateralReceiver: string, repayUnderlyingAmount: bigint, unlockedCollateralAmount: bigint];
      export interface OutputObject {sender: string, escrow: string, collateralReceiver: string, repayUnderlyingAmount: bigint, unlockedCollateralAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TakeQuoteEvent {
      export type InputTuple = [sender: AddressLike, escrowOwner: AddressLike, escrow: AddressLike, rfqInitialization: DataTypes.RFQInitializationStruct, takeQuotePreview: DataTypes.TakeQuotePreviewStruct, exerciseFee: BigNumberish, distPartner: AddressLike];
      export type OutputTuple = [sender: string, escrowOwner: string, escrow: string, rfqInitialization: DataTypes.RFQInitializationStructOutput, takeQuotePreview: DataTypes.TakeQuotePreviewStructOutput, exerciseFee: bigint, distPartner: string];
      export interface OutputObject {sender: string, escrowOwner: string, escrow: string, rfqInitialization: DataTypes.RFQInitializationStructOutput, takeQuotePreview: DataTypes.TakeQuotePreviewStructOutput, exerciseFee: bigint, distPartner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TakeSwapQuoteEvent {
      export type InputTuple = [sender: AddressLike, to: AddressLike, maker: AddressLike, swapQuote: DataTypes.SwapQuoteStruct];
      export type OutputTuple = [sender: string, to: string, maker: string, swapQuote: DataTypes.SwapQuoteStructOutput];
      export interface OutputObject {sender: string, to: string, maker: string, swapQuote: DataTypes.SwapQuoteStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [token: AddressLike, from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [token: string, from: string, to: string, value: bigint];
      export interface OutputObject {token: string, from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferOwnershipEvent {
      export type InputTuple = [escrow: AddressLike, oldOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [escrow: string, oldOwner: string, newOwner: string];
      export interface OutputObject {escrow: string, oldOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [sender: AddressLike, escrow: AddressLike, to: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, escrow: string, to: string, token: string, amount: bigint];
      export interface OutputObject {sender: string, escrow: string, to: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawFromEscrowAndCreateAuctionEvent {
      export type InputTuple = [escrowOwner: AddressLike, oldEscrow: AddressLike, newEscrow: AddressLike, auctionInitialization: DataTypes.AuctionInitializationStruct];
      export type OutputTuple = [escrowOwner: string, oldEscrow: string, newEscrow: string, auctionInitialization: DataTypes.AuctionInitializationStructOutput];
      export interface OutputObject {escrowOwner: string, oldEscrow: string, newEscrow: string, auctionInitialization: DataTypes.AuctionInitializationStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Router extends BaseContract {
    
    connect(runner?: ContractRunner | null): Router;
    waitForDeployment(): Promise<this>;

    interface: RouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bidOnAuction: TypedContractMethod<
      [escrow: AddressLike, optionReceiver: AddressLike, relBid: BigNumberish, _refSpot: BigNumberish, _oracleData: BytesLike[], ],
      [[DataTypes.BidPreviewStructOutput, string] & {preview: DataTypes.BidPreviewStructOutput, distPartner: string }],
      'nonpayable'
    >
    

    
    borrow: TypedContractMethod<
      [escrow: AddressLike, underlyingReceiver: AddressLike, borrowUnderlyingAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createAuction: TypedContractMethod<
      [escrowOwner: AddressLike, auctionInitialization: DataTypes.AuctionInitializationStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    emitTransferEvent: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    emitTransferOwnershipEvent: TypedContractMethod<
      [oldOwner: AddressLike, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    escrowImpl: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    exercise: TypedContractMethod<
      [escrow: AddressLike, underlyingReceiver: AddressLike, underlyingAmount: BigNumberish, payInSettlementToken: boolean, oracleData: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    feeHandler: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getEscrows: TypedContractMethod<
      [from: BigNumberish, numElements: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getExerciseFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMatchFees: TypedContractMethod<
      [distPartner: AddressLike, optionPremium: BigNumberish, optionInfo: DataTypes.OptionInfoStruct, ],
      [[bigint, bigint] & {matchFeeProtocol: bigint, matchFeeDistPartner: bigint }],
      'view'
    >
    

    
    getMintFees: TypedContractMethod<
      [distPartner: AddressLike, notional: BigNumberish, ],
      [[bigint, bigint] & {mintFeeProtocol: bigint, mintFeeDistPartner: bigint }],
      'view'
    >
    

    
    handleOffChainVoting: TypedContractMethod<
      [escrow: AddressLike, spaceId: BytesLike, delegate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    handleOnChainVoting: TypedContractMethod<
      [escrow: AddressLike, delegate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isEscrow: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isQuoteUsed: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isSwapQuoteUsed: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    mintOption: TypedContractMethod<
      [optionReceiver: AddressLike, escrowOwner: AddressLike, optionInfo: DataTypes.OptionInfoStruct, optionNaming: DataTypes.OptionNamingStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    numEscrows: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    previewTakeQuote: TypedContractMethod<
      [rfqInitialization: DataTypes.RFQInitializationStruct, distPartner: AddressLike, ],
      [DataTypes.TakeQuotePreviewStructOutput],
      'view'
    >
    

    
    quotesPaused: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    repay: TypedContractMethod<
      [escrow: AddressLike, collateralReceiver: AddressLike, repayUnderlyingAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeHandler: TypedContractMethod<
      [newFeeHandler: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeQuote: TypedContractMethod<
      [escrowOwner: AddressLike, rfqInitialization: DataTypes.RFQInitializationStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    takeSwapQuote: TypedContractMethod<
      [to: AddressLike, swapQuote: DataTypes.SwapQuoteStruct, ],
      [void],
      'nonpayable'
    >
    

    
    togglePauseQuotes: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [escrow: AddressLike, to: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFromEscrowAndCreateAuction: TypedContractMethod<
      [oldEscrow: AddressLike, escrowOwner: AddressLike, auctionInitialization: DataTypes.AuctionInitializationStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bidOnAuction'): TypedContractMethod<
      [escrow: AddressLike, optionReceiver: AddressLike, relBid: BigNumberish, _refSpot: BigNumberish, _oracleData: BytesLike[], ],
      [[DataTypes.BidPreviewStructOutput, string] & {preview: DataTypes.BidPreviewStructOutput, distPartner: string }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'borrow'): TypedContractMethod<
      [escrow: AddressLike, underlyingReceiver: AddressLike, borrowUnderlyingAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [escrowOwner: AddressLike, auctionInitialization: DataTypes.AuctionInitializationStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emitTransferEvent'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emitTransferOwnershipEvent'): TypedContractMethod<
      [oldOwner: AddressLike, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowImpl'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'exercise'): TypedContractMethod<
      [escrow: AddressLike, underlyingReceiver: AddressLike, underlyingAmount: BigNumberish, payInSettlementToken: boolean, oracleData: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeHandler'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrows'): TypedContractMethod<
      [from: BigNumberish, numElements: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getExerciseFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMatchFees'): TypedContractMethod<
      [distPartner: AddressLike, optionPremium: BigNumberish, optionInfo: DataTypes.OptionInfoStruct, ],
      [[bigint, bigint] & {matchFeeProtocol: bigint, matchFeeDistPartner: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getMintFees'): TypedContractMethod<
      [distPartner: AddressLike, notional: BigNumberish, ],
      [[bigint, bigint] & {mintFeeProtocol: bigint, mintFeeDistPartner: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'handleOffChainVoting'): TypedContractMethod<
      [escrow: AddressLike, spaceId: BytesLike, delegate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'handleOnChainVoting'): TypedContractMethod<
      [escrow: AddressLike, delegate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isEscrow'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isQuoteUsed'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isSwapQuoteUsed'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintOption'): TypedContractMethod<
      [optionReceiver: AddressLike, escrowOwner: AddressLike, optionInfo: DataTypes.OptionInfoStruct, optionNaming: DataTypes.OptionNamingStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'numEscrows'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'previewTakeQuote'): TypedContractMethod<
      [rfqInitialization: DataTypes.RFQInitializationStruct, distPartner: AddressLike, ],
      [DataTypes.TakeQuotePreviewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'quotesPaused'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repay'): TypedContractMethod<
      [escrow: AddressLike, collateralReceiver: AddressLike, repayUnderlyingAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeHandler'): TypedContractMethod<
      [newFeeHandler: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeQuote'): TypedContractMethod<
      [escrowOwner: AddressLike, rfqInitialization: DataTypes.RFQInitializationStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'takeSwapQuote'): TypedContractMethod<
      [to: AddressLike, swapQuote: DataTypes.SwapQuoteStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'togglePauseQuotes'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [escrow: AddressLike, to: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFromEscrowAndCreateAuction'): TypedContractMethod<
      [oldEscrow: AddressLike, escrowOwner: AddressLike, auctionInitialization: DataTypes.AuctionInitializationStruct, distPartner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BidOnAuction'): TypedContractEvent<BidOnAuctionEvent.InputTuple, BidOnAuctionEvent.OutputTuple, BidOnAuctionEvent.OutputObject>;
getEvent(key: 'Borrow'): TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
getEvent(key: 'CreateAuction'): TypedContractEvent<CreateAuctionEvent.InputTuple, CreateAuctionEvent.OutputTuple, CreateAuctionEvent.OutputObject>;
getEvent(key: 'Exercise'): TypedContractEvent<ExerciseEvent.InputTuple, ExerciseEvent.OutputTuple, ExerciseEvent.OutputObject>;
getEvent(key: 'MintOption'): TypedContractEvent<MintOptionEvent.InputTuple, MintOptionEvent.OutputTuple, MintOptionEvent.OutputObject>;
getEvent(key: 'NewFeeHandler'): TypedContractEvent<NewFeeHandlerEvent.InputTuple, NewFeeHandlerEvent.OutputTuple, NewFeeHandlerEvent.OutputObject>;
getEvent(key: 'OffChainVotingDelegation'): TypedContractEvent<OffChainVotingDelegationEvent.InputTuple, OffChainVotingDelegationEvent.OutputTuple, OffChainVotingDelegationEvent.OutputObject>;
getEvent(key: 'OnChainVotingDelegation'): TypedContractEvent<OnChainVotingDelegationEvent.InputTuple, OnChainVotingDelegationEvent.OutputTuple, OnChainVotingDelegationEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PauseQuotes'): TypedContractEvent<PauseQuotesEvent.InputTuple, PauseQuotesEvent.OutputTuple, PauseQuotesEvent.OutputObject>;
getEvent(key: 'Repay'): TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
getEvent(key: 'TakeQuote'): TypedContractEvent<TakeQuoteEvent.InputTuple, TakeQuoteEvent.OutputTuple, TakeQuoteEvent.OutputObject>;
getEvent(key: 'TakeSwapQuote'): TypedContractEvent<TakeSwapQuoteEvent.InputTuple, TakeSwapQuoteEvent.OutputTuple, TakeSwapQuoteEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TransferOwnership'): TypedContractEvent<TransferOwnershipEvent.InputTuple, TransferOwnershipEvent.OutputTuple, TransferOwnershipEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
getEvent(key: 'WithdrawFromEscrowAndCreateAuction'): TypedContractEvent<WithdrawFromEscrowAndCreateAuctionEvent.InputTuple, WithdrawFromEscrowAndCreateAuctionEvent.OutputTuple, WithdrawFromEscrowAndCreateAuctionEvent.OutputObject>;

    filters: {
      
      'BidOnAuction(address,address,address,tuple,address)': TypedContractEvent<BidOnAuctionEvent.InputTuple, BidOnAuctionEvent.OutputTuple, BidOnAuctionEvent.OutputObject>;
      BidOnAuction: TypedContractEvent<BidOnAuctionEvent.InputTuple, BidOnAuctionEvent.OutputTuple, BidOnAuctionEvent.OutputObject>;
    

      'Borrow(address,address,address,uint128,uint256,uint256)': TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
      Borrow: TypedContractEvent<BorrowEvent.InputTuple, BorrowEvent.OutputTuple, BorrowEvent.OutputObject>;
    

      'CreateAuction(address,address,tuple,uint96,address)': TypedContractEvent<CreateAuctionEvent.InputTuple, CreateAuctionEvent.OutputTuple, CreateAuctionEvent.OutputObject>;
      CreateAuction: TypedContractEvent<CreateAuctionEvent.InputTuple, CreateAuctionEvent.OutputTuple, CreateAuctionEvent.OutputObject>;
    

      'Exercise(address,address,address,uint256,uint256)': TypedContractEvent<ExerciseEvent.InputTuple, ExerciseEvent.OutputTuple, ExerciseEvent.OutputObject>;
      Exercise: TypedContractEvent<ExerciseEvent.InputTuple, ExerciseEvent.OutputTuple, ExerciseEvent.OutputObject>;
    

      'MintOption(address,address,address,tuple,uint256,uint256,address)': TypedContractEvent<MintOptionEvent.InputTuple, MintOptionEvent.OutputTuple, MintOptionEvent.OutputObject>;
      MintOption: TypedContractEvent<MintOptionEvent.InputTuple, MintOptionEvent.OutputTuple, MintOptionEvent.OutputObject>;
    

      'NewFeeHandler(address,address)': TypedContractEvent<NewFeeHandlerEvent.InputTuple, NewFeeHandlerEvent.OutputTuple, NewFeeHandlerEvent.OutputObject>;
      NewFeeHandler: TypedContractEvent<NewFeeHandlerEvent.InputTuple, NewFeeHandlerEvent.OutputTuple, NewFeeHandlerEvent.OutputObject>;
    

      'OffChainVotingDelegation(address,bytes32,address)': TypedContractEvent<OffChainVotingDelegationEvent.InputTuple, OffChainVotingDelegationEvent.OutputTuple, OffChainVotingDelegationEvent.OutputObject>;
      OffChainVotingDelegation: TypedContractEvent<OffChainVotingDelegationEvent.InputTuple, OffChainVotingDelegationEvent.OutputTuple, OffChainVotingDelegationEvent.OutputObject>;
    

      'OnChainVotingDelegation(address,address)': TypedContractEvent<OnChainVotingDelegationEvent.InputTuple, OnChainVotingDelegationEvent.OutputTuple, OnChainVotingDelegationEvent.OutputObject>;
      OnChainVotingDelegation: TypedContractEvent<OnChainVotingDelegationEvent.InputTuple, OnChainVotingDelegationEvent.OutputTuple, OnChainVotingDelegationEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PauseQuotes(address,bool)': TypedContractEvent<PauseQuotesEvent.InputTuple, PauseQuotesEvent.OutputTuple, PauseQuotesEvent.OutputObject>;
      PauseQuotes: TypedContractEvent<PauseQuotesEvent.InputTuple, PauseQuotesEvent.OutputTuple, PauseQuotesEvent.OutputObject>;
    

      'Repay(address,address,address,uint128,uint256)': TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
      Repay: TypedContractEvent<RepayEvent.InputTuple, RepayEvent.OutputTuple, RepayEvent.OutputObject>;
    

      'TakeQuote(address,address,address,tuple,tuple,uint96,address)': TypedContractEvent<TakeQuoteEvent.InputTuple, TakeQuoteEvent.OutputTuple, TakeQuoteEvent.OutputObject>;
      TakeQuote: TypedContractEvent<TakeQuoteEvent.InputTuple, TakeQuoteEvent.OutputTuple, TakeQuoteEvent.OutputObject>;
    

      'TakeSwapQuote(address,address,address,tuple)': TypedContractEvent<TakeSwapQuoteEvent.InputTuple, TakeSwapQuoteEvent.OutputTuple, TakeSwapQuoteEvent.OutputObject>;
      TakeSwapQuote: TypedContractEvent<TakeSwapQuoteEvent.InputTuple, TakeSwapQuoteEvent.OutputTuple, TakeSwapQuoteEvent.OutputObject>;
    

      'Transfer(address,address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TransferOwnership(address,address,address)': TypedContractEvent<TransferOwnershipEvent.InputTuple, TransferOwnershipEvent.OutputTuple, TransferOwnershipEvent.OutputObject>;
      TransferOwnership: TypedContractEvent<TransferOwnershipEvent.InputTuple, TransferOwnershipEvent.OutputTuple, TransferOwnershipEvent.OutputObject>;
    

      'Withdraw(address,address,address,address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    

      'WithdrawFromEscrowAndCreateAuction(address,address,address,tuple)': TypedContractEvent<WithdrawFromEscrowAndCreateAuctionEvent.InputTuple, WithdrawFromEscrowAndCreateAuctionEvent.OutputTuple, WithdrawFromEscrowAndCreateAuctionEvent.OutputObject>;
      WithdrawFromEscrowAndCreateAuction: TypedContractEvent<WithdrawFromEscrowAndCreateAuctionEvent.InputTuple, WithdrawFromEscrowAndCreateAuctionEvent.OutputTuple, WithdrawFromEscrowAndCreateAuctionEvent.OutputObject>;
    
    };
  }