/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace DataTypes {
      
    export type MatchFeePerPairStruct = {isSet: boolean, matchFee: BigNumberish}

    export type MatchFeePerPairStructOutput = [isSet: boolean, matchFee: bigint] & {isSet: boolean, matchFee: bigint }
  

    export type AdvancedSettingsStruct = {borrowCap: BigNumberish, oracle: AddressLike, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: AddressLike}

    export type AdvancedSettingsStructOutput = [borrowCap: bigint, oracle: string, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: string] & {borrowCap: bigint, oracle: string, premiumTokenIsUnderlying: boolean, votingDelegationAllowed: boolean, allowedDelegateRegistry: string }
  

    export type OptionInfoStruct = {underlyingToken: AddressLike, expiry: BigNumberish, settlementToken: AddressLike, earliestExercise: BigNumberish, notional: BigNumberish, strike: BigNumberish, advancedSettings: DataTypes.AdvancedSettingsStruct}

    export type OptionInfoStructOutput = [underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput] & {underlyingToken: string, expiry: bigint, settlementToken: string, earliestExercise: bigint, notional: bigint, strike: bigint, advancedSettings: DataTypes.AdvancedSettingsStructOutput }
  
    }

  export interface IFeeHandlerInterface extends Interface {
    getFunction(nameOrSignature: "distPartnerFeeShare" | "exerciseFee" | "getMatchFeeInfo" | "getMintFeeInfo" | "matchFee" | "provisionFees" | "setDistPartnerFeeShares" | "setExerciseFee" | "setMatchFee" | "setMatchFeesPerPair" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProvisionFees" | "SetDistPartnerFeeShares" | "SetExerciseFee" | "SetMatchFee" | "SetMatchFeesPerPair" | "SetMintFee" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'distPartnerFeeShare', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'exerciseFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMatchFeeInfo', values: [AddressLike, BigNumberish, DataTypes.OptionInfoStruct]): string;
encodeFunctionData(functionFragment: 'getMintFeeInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'matchFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'provisionFees', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDistPartnerFeeShares', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'setExerciseFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMatchFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMatchFeesPerPair', values: [AddressLike[], AddressLike[], DataTypes.MatchFeePerPairStruct[]]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'distPartnerFeeShare', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exerciseFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMatchFeeInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMintFeeInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'provisionFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDistPartnerFeeShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExerciseFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMatchFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMatchFeesPerPair', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace ProvisionFeesEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, amount: bigint];
      export interface OutputObject {token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetDistPartnerFeeSharesEvent {
      export type InputTuple = [accounts: AddressLike[], feeShares: BigNumberish[]];
      export type OutputTuple = [accounts: string[], feeShares: bigint[]];
      export interface OutputObject {accounts: string[], feeShares: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetExerciseFeeEvent {
      export type InputTuple = [exerciseFee: BigNumberish];
      export type OutputTuple = [exerciseFee: bigint];
      export interface OutputObject {exerciseFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetMatchFeeEvent {
      export type InputTuple = [matchFee: BigNumberish];
      export type OutputTuple = [matchFee: bigint];
      export interface OutputObject {matchFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetMatchFeesPerPairEvent {
      export type InputTuple = [underlyingTokens: AddressLike[], settlementTokens: AddressLike[], matchFeesPerPair: DataTypes.MatchFeePerPairStruct[]];
      export type OutputTuple = [underlyingTokens: string[], settlementTokens: string[], matchFeesPerPair: DataTypes.MatchFeePerPairStructOutput[]];
      export interface OutputObject {underlyingTokens: string[], settlementTokens: string[], matchFeesPerPair: DataTypes.MatchFeePerPairStructOutput[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetMintFeeEvent {
      export type InputTuple = [mintFee: BigNumberish];
      export type OutputTuple = [mintFee: bigint];
      export interface OutputObject {mintFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [to: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, token: string, amount: bigint];
      export interface OutputObject {to: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IFeeHandler extends BaseContract {
    
    connect(runner?: ContractRunner | null): IFeeHandler;
    waitForDeployment(): Promise<this>;

    interface: IFeeHandlerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    distPartnerFeeShare: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    exerciseFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMatchFeeInfo: TypedContractMethod<
      [distPartner: AddressLike, optionPremium: BigNumberish, optionInfo: DataTypes.OptionInfoStruct, ],
      [[bigint, bigint] & {_matchFee: bigint, _matchFeeDistPartnerShare: bigint }],
      'view'
    >
    

    
    getMintFeeInfo: TypedContractMethod<
      [distPartner: AddressLike, ],
      [[bigint, bigint] & {_mintFee: bigint, _mintFeeDistPartnerShare: bigint }],
      'view'
    >
    

    
    matchFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    provisionFees: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDistPartnerFeeShares: TypedContractMethod<
      [accounts: AddressLike[], feeShares: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    setExerciseFee: TypedContractMethod<
      [_exerciseFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMatchFee: TypedContractMethod<
      [_matchFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMatchFeesPerPair: TypedContractMethod<
      [underlyingTokens: AddressLike[], settlementTokens: AddressLike[], _matchFeePerPair: DataTypes.MatchFeePerPairStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [to: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'distPartnerFeeShare'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'exerciseFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMatchFeeInfo'): TypedContractMethod<
      [distPartner: AddressLike, optionPremium: BigNumberish, optionInfo: DataTypes.OptionInfoStruct, ],
      [[bigint, bigint] & {_matchFee: bigint, _matchFeeDistPartnerShare: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getMintFeeInfo'): TypedContractMethod<
      [distPartner: AddressLike, ],
      [[bigint, bigint] & {_mintFee: bigint, _mintFeeDistPartnerShare: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'matchFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'provisionFees'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDistPartnerFeeShares'): TypedContractMethod<
      [accounts: AddressLike[], feeShares: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setExerciseFee'): TypedContractMethod<
      [_exerciseFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMatchFee'): TypedContractMethod<
      [_matchFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMatchFeesPerPair'): TypedContractMethod<
      [underlyingTokens: AddressLike[], settlementTokens: AddressLike[], _matchFeePerPair: DataTypes.MatchFeePerPairStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [to: AddressLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProvisionFees'): TypedContractEvent<ProvisionFeesEvent.InputTuple, ProvisionFeesEvent.OutputTuple, ProvisionFeesEvent.OutputObject>;
getEvent(key: 'SetDistPartnerFeeShares'): TypedContractEvent<SetDistPartnerFeeSharesEvent.InputTuple, SetDistPartnerFeeSharesEvent.OutputTuple, SetDistPartnerFeeSharesEvent.OutputObject>;
getEvent(key: 'SetExerciseFee'): TypedContractEvent<SetExerciseFeeEvent.InputTuple, SetExerciseFeeEvent.OutputTuple, SetExerciseFeeEvent.OutputObject>;
getEvent(key: 'SetMatchFee'): TypedContractEvent<SetMatchFeeEvent.InputTuple, SetMatchFeeEvent.OutputTuple, SetMatchFeeEvent.OutputObject>;
getEvent(key: 'SetMatchFeesPerPair'): TypedContractEvent<SetMatchFeesPerPairEvent.InputTuple, SetMatchFeesPerPairEvent.OutputTuple, SetMatchFeesPerPairEvent.OutputObject>;
getEvent(key: 'SetMintFee'): TypedContractEvent<SetMintFeeEvent.InputTuple, SetMintFeeEvent.OutputTuple, SetMintFeeEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'ProvisionFees(address,uint256)': TypedContractEvent<ProvisionFeesEvent.InputTuple, ProvisionFeesEvent.OutputTuple, ProvisionFeesEvent.OutputObject>;
      ProvisionFees: TypedContractEvent<ProvisionFeesEvent.InputTuple, ProvisionFeesEvent.OutputTuple, ProvisionFeesEvent.OutputObject>;
    

      'SetDistPartnerFeeShares(address[],uint256[])': TypedContractEvent<SetDistPartnerFeeSharesEvent.InputTuple, SetDistPartnerFeeSharesEvent.OutputTuple, SetDistPartnerFeeSharesEvent.OutputObject>;
      SetDistPartnerFeeShares: TypedContractEvent<SetDistPartnerFeeSharesEvent.InputTuple, SetDistPartnerFeeSharesEvent.OutputTuple, SetDistPartnerFeeSharesEvent.OutputObject>;
    

      'SetExerciseFee(uint96)': TypedContractEvent<SetExerciseFeeEvent.InputTuple, SetExerciseFeeEvent.OutputTuple, SetExerciseFeeEvent.OutputObject>;
      SetExerciseFee: TypedContractEvent<SetExerciseFeeEvent.InputTuple, SetExerciseFeeEvent.OutputTuple, SetExerciseFeeEvent.OutputObject>;
    

      'SetMatchFee(uint256)': TypedContractEvent<SetMatchFeeEvent.InputTuple, SetMatchFeeEvent.OutputTuple, SetMatchFeeEvent.OutputObject>;
      SetMatchFee: TypedContractEvent<SetMatchFeeEvent.InputTuple, SetMatchFeeEvent.OutputTuple, SetMatchFeeEvent.OutputObject>;
    

      'SetMatchFeesPerPair(address[],address[],tuple[])': TypedContractEvent<SetMatchFeesPerPairEvent.InputTuple, SetMatchFeesPerPairEvent.OutputTuple, SetMatchFeesPerPairEvent.OutputObject>;
      SetMatchFeesPerPair: TypedContractEvent<SetMatchFeesPerPairEvent.InputTuple, SetMatchFeesPerPairEvent.OutputTuple, SetMatchFeesPerPairEvent.OutputObject>;
    

      'SetMintFee(uint256)': TypedContractEvent<SetMintFeeEvent.InputTuple, SetMintFeeEvent.OutputTuple, SetMintFeeEvent.OutputObject>;
      SetMintFee: TypedContractEvent<SetMintFeeEvent.InputTuple, SetMintFeeEvent.OutputTuple, SetMintFeeEvent.OutputObject>;
    

      'Withdraw(address,address,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }