/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IOracleAdapterInterface extends Interface {
    getFunction(nameOrSignature: "ETH_USD_ORACLE" | "MAX_TIME_SINCE_LAST_UPDATE" | "ORACLE_MAPPING_IS_APPEND_ONLY" | "WETH" | "addOracleMapping" | "getPrice" | "getPriceOfToken" | "oracleInfos"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddOracleMapping"): EventFragment;

    encodeFunctionData(functionFragment: 'ETH_USD_ORACLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_TIME_SINCE_LAST_UPDATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORACLE_MAPPING_IS_APPEND_ONLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'WETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'addOracleMapping', values: [AddressLike[], AddressLike[]]): string;
encodeFunctionData(functionFragment: 'getPrice', values: [AddressLike, AddressLike, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'getPriceOfToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'oracleInfos', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ETH_USD_ORACLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_TIME_SINCE_LAST_UPDATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORACLE_MAPPING_IS_APPEND_ONLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOracleMapping', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPriceOfToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleInfos', data: BytesLike): Result;
  }

  
    export namespace AddOracleMappingEvent {
      export type InputTuple = [tokenAddress: AddressLike, oracleAddress: AddressLike];
      export type OutputTuple = [tokenAddress: string, oracleAddress: string];
      export interface OutputObject {tokenAddress: string, oracleAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IOracleAdapter extends BaseContract {
    
    connect(runner?: ContractRunner | null): IOracleAdapter;
    waitForDeployment(): Promise<this>;

    interface: IOracleAdapterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ETH_USD_ORACLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_TIME_SINCE_LAST_UPDATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ORACLE_MAPPING_IS_APPEND_ONLY: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    WETH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addOracleMapping: TypedContractMethod<
      [tokenAddrs: AddressLike[], oracleAddrs: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    getPrice: TypedContractMethod<
      [token: AddressLike, quoteToken: AddressLike, oracleData: BytesLike[], ],
      [bigint],
      'view'
    >
    

    
    getPriceOfToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    oracleInfos: TypedContractMethod<
      [token: AddressLike, ],
      [[string, bigint] & {oracleAddr: string, decimals: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ETH_USD_ORACLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_TIME_SINCE_LAST_UPDATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ORACLE_MAPPING_IS_APPEND_ONLY'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'WETH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addOracleMapping'): TypedContractMethod<
      [tokenAddrs: AddressLike[], oracleAddrs: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [token: AddressLike, quoteToken: AddressLike, oracleData: BytesLike[], ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPriceOfToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracleInfos'): TypedContractMethod<
      [token: AddressLike, ],
      [[string, bigint] & {oracleAddr: string, decimals: bigint }],
      'view'
    >;

    getEvent(key: 'AddOracleMapping'): TypedContractEvent<AddOracleMappingEvent.InputTuple, AddOracleMappingEvent.OutputTuple, AddOracleMappingEvent.OutputObject>;

    filters: {
      
      'AddOracleMapping(address,address)': TypedContractEvent<AddOracleMappingEvent.InputTuple, AddOracleMappingEvent.OutputTuple, AddOracleMappingEvent.OutputObject>;
      AddOracleMapping: TypedContractEvent<AddOracleMappingEvent.InputTuple, AddOracleMappingEvent.OutputTuple, AddOracleMappingEvent.OutputObject>;
    
    };
  }